const itauLayout240 = [
  {
    fieldName: "bank_code",
    positionStart: 1,
    positionEnd: 3,
    positionLength: 3,
    picture: "9",
    defaultValue: "",
  },
  {
    fieldName: "batch_code",
    positionStart: 4,
    positionEnd: 7,
    positionLength: 4,
    picture: "9",
    defaultValue: "",
  },
  {
    fieldName: "register_type",
    positionStart: 8,
    positionEnd: 8,
    positionLength: 1,
    picture: "9",
    defaultValue: "",
  },
  {
    fieldName: "register_number",
    positionStart: 9,
    positionEnd: 13,
    positionLength: 5,
    picture: "9",
    defaultValue: "",
  },
  {
    fieldName: "segment",
    positionStart: 14,
    positionEnd: 14,
    positionLength: 1,
    picture: "X",
    defaultValue: "",
  },
  {
    fieldName: "move_type",
    positionStart: 15,
    positionEnd: 17,
    positionLength: 3,
    picture: "9",
    defaultValue: "",
  },
  {
    fieldName: "chamber",
    positionStart: 18,
    positionEnd: 20,
    positionLength: 3,
    picture: "9",
    defaultValue: "",
  },
  {
    fieldName: "favored_bank",
    positionStart: 21,
    positionEnd: 23,
    positionLength: 3,
    picture: "9",
    defaultValue: "",
  },
  {
    fieldName: "favored_agency_and_account",
    positionStart: 24,
    positionEnd: 43,
    positionLength: 20,
    picture: "X",
    defaultValue: "",
  },
  {
    fieldName: "favored_name",
    positionStart: 44,
    positionEnd: 73,
    positionLength: 30,
    picture: "X",
    defaultValue: "",
  },
  {
    fieldName: "my_document_number",
    positionStart: 74,
    positionEnd: 93,
    positionLength: 20,
    picture: "X",
    defaultValue: "",
  },
  {
    fieldName: "pay_day",
    positionStart: 94,
    positionEnd: 101,
    positionLength: 8,
    picture: "9",
    defaultValue: "",
  },
  {
    fieldName: "currency_type",
    positionStart: 102,
    positionEnd: 104,
    positionLength: 3,
    picture: "X",
    defaultValue: "",
  },
  {
    fieldName: "isbp_code",
    positionStart: 105,
    positionEnd: 112,
    positionLength: 8,
    picture: "X",
    defaultValue: "",
  },
  {
    fieldName: "register_complement_zeroes",
    positionStart: 113,
    positionEnd: 119,
    positionLength: 7,
    picture: "9",
    defaultValue: "",
  },
  {
    fieldName: "payment_amount",
    positionStart: 120,
    positionEnd: 134,
    positionLength: 15,
    picture: "9",
    defaultValue: "",
  },
  {
    fieldName: "bank_document_number_return",
    positionStart: 135,
    positionEnd: 149,
    positionLength: 15,
    picture: "X",
    defaultValue: "",
  },
  {
    fieldName: "register_complement_white_space",
    positionStart: 150,
    positionEnd: 154,
    positionLength: 5,
    picture: "X",
    defaultValue: "",
  },
  {
    fieldName: "payment_complete_date_return",
    positionStart: 155,
    positionEnd: 162,
    positionLength: 8,
    picture: "9",
    defaultValue: "",
  },
  {
    fieldName: "actual_payment_amount_return",
    positionStart: 163,
    positionEnd: 177,
    positionLength: 15,
    picture: "9",
    defaultValue: "",
  },
  {
    fieldName: "goal_detail",
    positionStart: 178,
    positionEnd: 197,
    positionLength: 20,
    picture: "X",
    defaultValue: "",
  },
  {
    fieldName: "document_number_operation_return",
    positionStart: 198,
    positionEnd: 203,
    positionLength: 6,
    picture: "9",
    defaultValue: "",
  },
  {
    fieldName: "document_registration_number",
    positionStart: 204,
    positionEnd: 217,
    positionLength: 14,
    picture: "9",
    defaultValue: "",
  },
  {
    fieldName: "purpose_of_the_document_and_employee_status",
    positionStart: 218,
    positionEnd: 219,
    positionLength: 2,
    picture: "X",
    defaultValue: "",
  },
  {
    fieldName: "goal_ted",
    positionStart: 220,
    positionEnd: 224,
    positionLength: 5,
    picture: "X",
    defaultValue: "",
  },
  {
    fieldName: "register_complement_white_space_2",
    positionStart: 225,
    positionEnd: 229,
    positionLength: 5,
    picture: "X",
    defaultValue: "",
  },
  {
    fieldName: "notice_favored",
    positionStart: 230,
    positionEnd: 230,
    positionLength: 1,
    picture: "X",
    defaultValue: "",
  },
  {
    fieldName: "occurrences_code_return",
    positionStart: 231,
    positionEnd: 240,
    positionLength: 10,
    picture: "X",
    defaultValue: "",
  }
]

module.exports = { itauLayout240 }